version: "3"
services:
  dovecot:
    build: ./tbp-dovecot
    image: tbp/dovecot
    restart: always
    stdin_open: true
    tty: true
    volumes:
     - ./tbp-dovecot/log:/var/log
     - postfix-spool:/var/spool/postfix
  postfix:
    build: ./tbp-postfix
    image: tbp/postfix
    ports:
     - "25:25"
    restart: always
    stdin_open: true
    tty: true
    volumes:
     - ./tbp-postfix/mail:/var/mail
     - postfix-spool:/var/spool/postfix
     - ./tbp-postfix/log:/var/log
volumes:
  postfix-spool:
