version: "3"
services:
  dovecot:
    build: ./tbp-dovecot
    image: tbp/dovecot
    restart: always
    stdin_open: true
    tty: true
    volumes:
     - postfix-spool:/var/spool/postfix
  postfix:
    build: ./tbp-postfix
    image: tbp/postfix
    ports:
     - "25:25"
    restart: always
    stdin_open: true
    tty: true
    volumes:
     - postfix-mail:/var/mail
     - postfix-spool:/var/spool/postfix
volumes:
  postfix-spool:
  postfix-mail: